### ISSUE TITLE
It have new future like use WEBRTC to local call center in local?

### ISSUE THREAD

**Issue by tanpham380** [clemlesne/call-center-ai#262]

**Comment by clemlesne** [comment]
I don't understand your question, can you elaborate?

**Comment by tanpham380** [comment]
It have review your project it use Microsoft call center service right?. I want know this project will have development local call center?

**Comment by clemlesne** [comment]
You can connect your on-prem and Azure with a compatible SBC hardware: https://learn.microsoft.com/en-us/azure/communication-services/concepts/telephony/telephony-concept#azure-direct-routing

**Comment by tanpham380** [comment]
ok I will try this, thanks you so much
